### ISSUE TITLE
Ignore certain variables

### ISSUE THREAD

**Issue by mandrejic** [tobiaszuercher/transformer#20]
Is there an escape character to tell the transformer to ignore certain variables?
For example, Event Log target uses this syntax: ${longdate}|${level:uppercase=true}|${logger}|${message}

And longdate, level, logger and message should not be transformed.

Does the tool support this?

**Comment by tobiaszuercher** [comment]
hi @mandrejic 
yes there is support for it! i've just recognized that this is not documented :(. i'll add the documentation later.

to escape just use `_$_` instead of `$`:
`_$_{longdate}|_$_{level:uppercase=true}|_$_{logger}|_$_{message}`

this hidden feature is tested here: https://github.com/tobiaszuercher/transformer/blob/master/src/Transformer.Tests/VariableResolverTests.cs#L369-375

**Comment by mandrejic** [comment]
Thanks @tobiaszuercher
